version: '3.8'

services:
  reverse-proxy:
    build: 
      context: ./reverse-proxy
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    networks:
      - mysql_node

  server:
    build: 
      context: ./server
    restart: unless-stopped
    ports:
      - "3000:3000"
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node app.js
    volumes:
      - ./server/app.js:/app/app.js
    depends_on:
      - db
    networks:
      - mysql_node

  db:
    build: 
      context: ./db
    restart: unless-stopped
    ports:
      - "3306:3306"
    tty: true
    networks:
      - mysql_node
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:

networks:
  mysql_node:
    driver: bridge