version: '3.8'

services:
  reverse-proxy:
    build: 
      context: ./reverse-proxy
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

  server:
    build: 
      context: ./server
    restart: unless-stopped
    ports:
      - "3000:3000"
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node app.js
    volumes:
      - ./server/app.js:/app.js
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
